"""create initial schema

Revision ID: a36cfcf238f7
Revises: 
Create Date: 2026-04-05 18:29:23.971534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36cfcf238f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_product_id'), 'audit_logs', ['product_id'], unique=False)
    op.create_table('organization_invites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'BILLING_MANAGER', 'MEMBER', name='orgrole'), nullable=False),
    sa.Column('invited_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_email_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_invites_email'), 'organization_invites', ['email'], unique=False)
    op.create_index(op.f('ix_organization_invites_token'), 'organization_invites', ['token'], unique=True)
    op.create_table('organization_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'BILLING_MANAGER', 'MEMBER', name='orgrole'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_permission_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('organization_member_id', sa.String(length=36), nullable=False),
    sa.Column('permission_group_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_member_id'], ['organization_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_group_id'], ['permission_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'organization_member_id', name='uq_product_permission_assignment_member')
    )
    op.create_table('sdk_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('config_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdk_keys_key'), 'sdk_keys', ['key'], unique=True)
    op.create_table('segment_conditions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('attribute', sa.String(length=255), nullable=False),
    sa.Column('comparator', sa.Enum('EQUALS', 'NOT_EQUALS', 'CONTAINS', 'NOT_CONTAINS', 'STARTS_WITH', 'NOT_STARTS_WITH', 'ENDS_WITH', 'NOT_ENDS_WITH', 'IS_ONE_OF', 'IS_NOT_ONE_OF', 'NUMBER_EQUALS', 'NUMBER_NOT_EQUALS', 'NUMBER_LESS', 'NUMBER_LESS_OR_EQUALS', 'NUMBER_GREATER', 'NUMBER_GREATER_OR_EQUALS', 'SEMVER_LESS', 'SEMVER_LESS_OR_EQUALS', 'SEMVER_GREATER', 'SEMVER_GREATER_OR_EQUALS', 'SEMVER_EQUALS', 'SEMVER_NOT_EQUALS', 'BEFORE', 'AFTER', 'REGEX_MATCH', 'REGEX_NOT_MATCH', 'ARRAY_CONTAINS', 'ARRAY_NOT_CONTAINS', name='comparator'), nullable=False),
    sa.Column('comparison_value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('config_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hint', sa.String(length=500), nullable=True),
    sa.Column('setting_type', sa.Enum('BOOLEAN', 'STRING', 'INT', 'DOUBLE', name='settingtype'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'key', name='uq_setting_config_key')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=False)
    op.create_table('webhooks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('config_id', sa.String(length=36), nullable=True),
    sa.Column('environment_id', sa.String(length=36), nullable=True),
    sa.Column('signing_secret', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['configs.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('setting_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['setting_id'], ['settings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting_values',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('setting_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('default_value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setting_id'], ['settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_id', 'environment_id', name='uq_setting_value_env')
    )
    op.create_table('webhook_delivery_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('webhook_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=255), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_delivery_attempts_created_at'), 'webhook_delivery_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_delivery_attempts_webhook_id'), 'webhook_delivery_attempts', ['webhook_id'], unique=False)
    op.create_table('percentage_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('setting_value_id', sa.String(length=36), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setting_value_id'], ['setting_values.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('targeting_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('setting_value_id', sa.String(length=36), nullable=False),
    sa.Column('served_value', sa.JSON(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setting_value_id'], ['setting_values.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conditions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('targeting_rule_id', sa.String(length=36), nullable=False),
    sa.Column('condition_type', sa.Enum('USER', 'FLAG', 'SEGMENT', name='conditiontype'), nullable=False),
    sa.Column('attribute', sa.String(length=255), nullable=True),
    sa.Column('comparator', sa.Enum('EQUALS', 'NOT_EQUALS', 'CONTAINS', 'NOT_CONTAINS', 'STARTS_WITH', 'NOT_STARTS_WITH', 'ENDS_WITH', 'NOT_ENDS_WITH', 'IS_ONE_OF', 'IS_NOT_ONE_OF', 'NUMBER_EQUALS', 'NUMBER_NOT_EQUALS', 'NUMBER_LESS', 'NUMBER_LESS_OR_EQUALS', 'NUMBER_GREATER', 'NUMBER_GREATER_OR_EQUALS', 'SEMVER_LESS', 'SEMVER_LESS_OR_EQUALS', 'SEMVER_GREATER', 'SEMVER_GREATER_OR_EQUALS', 'SEMVER_EQUALS', 'SEMVER_NOT_EQUALS', 'BEFORE', 'AFTER', 'REGEX_MATCH', 'REGEX_NOT_MATCH', 'ARRAY_CONTAINS', 'ARRAY_NOT_CONTAINS', name='comparator'), nullable=False),
    sa.Column('comparison_value', sa.JSON(), nullable=False),
    sa.Column('segment_id', sa.String(length=36), nullable=True),
    sa.Column('prerequisite_setting_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['prerequisite_setting_id'], ['settings.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.ForeignKeyConstraint(['targeting_rule_id'], ['targeting_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conditions')
    op.drop_table('targeting_rules')
    op.drop_table('percentage_options')
    op.drop_index(op.f('ix_webhook_delivery_attempts_webhook_id'), table_name='webhook_delivery_attempts')
    op.drop_index(op.f('ix_webhook_delivery_attempts_created_at'), table_name='webhook_delivery_attempts')
    op.drop_table('webhook_delivery_attempts')
    op.drop_table('setting_values')
    op.drop_table('setting_tags')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_table('segment_conditions')
    op.drop_index(op.f('ix_sdk_keys_key'), table_name='sdk_keys')
    op.drop_table('sdk_keys')
    op.drop_table('product_permission_assignments')
    op.drop_table('tags')
    op.drop_table('segments')
    op.drop_table('permission_groups')
    op.drop_table('environments')
    op.drop_table('configs')
    op.drop_table('products')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_organization_invites_token'), table_name='organization_invites')
    op.drop_index(op.f('ix_organization_invites_email'), table_name='organization_invites')
    op.drop_table('organization_invites')
    op.drop_index(op.f('ix_audit_logs_product_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
